config/routes.rb
Rails.application.routes.draw do
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  devise_for :users

  resources :posts

  get '/repost/:id', to: 'posts#repost'
  get '/quick_repost/:id', to: 'posts#quick_repost'
  get '/user/:username', to: 'users#show'
  get '/user/:username/post/:id', to: 'posts#show'
  get '/everyone', to: "posts#index"
  get '/followers', to: "users#followers"
  get '/followed', to: "users#followed"
  get '/user/:username/followed', to: 'users#followed'
  get '/user/:username/followers', to: 'users#followers'
  get '/follow/:id', to: 'users#follow'
  get '/unfollow/:id', to: 'users#unfollow'
  root 'posts#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TumblroSoupoKlon</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">TumblroSoupoKlon</a>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li id="li-everyone">
          <%= link_to 'Everyone', '/everyone' %>
        </li>
        <li id="li-followed">
          <%= get_followed_link %>
        </li>
        <li id="li-followers">
          <%= get_followers_link %>
        </li>
        <li id="li-hashtags">
          <%= link_to 'Tags', hashtags_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <%= link_to get_username_with_caret.html_safe, '#',  data: { toggle: "dropdown" } %>
          <ul class="dropdown-menu">
            <li>
              <%= get_profile_link %>
            </li>
            <li class="divider"></li>
            <li>
              <%= get_login_logout_link %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="modal fade" id="repostModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Reposted</h4>
      </div>
      <div id="repostBody">
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
      <% if alert %>
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <%= alert %>
        </div>
      <% end %>
      <% if notice %>
        <div class="alert alert-dismissable alert-success">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <%= notice %>
        </div>
      <% end %>
    </div>
    <div class="col-lg-3"></div>
  </div>
  <%= yield %>
  <div class="row margin_footer">
    <div class="col-lg-12 modal-footer">
      &copy;TumblroSoupoKlon
    </div>
  </div>
</div>
</body>
</html>